package awe.devikamehra.shademelange.Enum;

/**
 * Created by Devika on 05-04-2016.
 */

import android.graphics.Color;

public enum MaterialShadeEnum {

    RED_LIGHTEN_5(giveShadeInt("#FFEBEE")),
    RED_LIGHTEN_4(giveShadeInt("#FFCDD2")),
    RED_LIGHTEN_3(giveShadeInt("#EF9A9A")),
    RED_LIGHTEN_2(giveShadeInt("#E57373")),
    RED_LIGHTEN_1(giveShadeInt("#EF5350")),
    RED(giveShadeInt("#F44336")),
    RED_DARKEN_1(giveShadeInt("#E53935")),
    RED_DARKEN_2(giveShadeInt("#D32F2F")),
    RED_DARKEN_3(giveShadeInt("#C62828")),
    RED_DARKEN_4(giveShadeInt("#B71C1C")),
    RED_ACCENT_1(giveShadeInt("#FF8A80")),
    RED_ACCENT_2(giveShadeInt("#FF5252")),
    RED_ACCENT_3(giveShadeInt("#FF1744")),
    RED_ACCENT_4(giveShadeInt("#D50000")),
    
    PINK_LIGHTEN_5(giveShadeInt("#FCE4EC")),
    PINK_LIGHTEN_4(giveShadeInt("#F8BBD0")),
    PINK_LIGHTEN_3(giveShadeInt("#F48FB1")),
    PINK_LIGHTEN_2(giveShadeInt("#F06292")),
    PINK_LIGHTEN_1(giveShadeInt("#EC407A")),
    PINK(giveShadeInt("#E91E63")),
    PINK_DARKEN_1(giveShadeInt("#D81B60")),
    PINK_DARKEN_2(giveShadeInt("#C2185B")),
    PINK_DARKEN_3(giveShadeInt("#AD1457")),
    PINK_DARKEN_4(giveShadeInt("#880E4F")),
    PINK_ACCENT_1(giveShadeInt("#FF80AB")),
    PINK_ACCENT_2(giveShadeInt("#FF4081")),
    PINK_ACCENT_3(giveShadeInt("#F50057")),
    PINK_ACCENT_4(giveShadeInt("#C51162")),

    PURPLE_LIGHTEN_5(giveShadeInt("#F3E5F5")),
    PURPLE_LIGHTEN_4(giveShadeInt("#E1BEE7")),
    PURPLE_LIGHTEN_3(giveShadeInt("#CE93D8")),
    PURPLE_LIGHTEN_2(giveShadeInt("#BA68C8")),
    PURPLE_LIGHTEN_1(giveShadeInt("#AB47BC")),
    PURPLE(giveShadeInt("#9C27B0")),
    PURPLE_DARKEN_1(giveShadeInt("#8E24AA")),
    PURPLE_DARKEN_2(giveShadeInt("#7B1FA2")),
    PURPLE_DARKEN_3(giveShadeInt("#6A1B9A")),
    PURPLE_DARKEN_4(giveShadeInt("#4A148C")),
    PURPLE_ACCENT_1(giveShadeInt("#EA80FC")),
    PURPLE_ACCENT_2(giveShadeInt("#E040FB")),
    PURPLE_ACCENT_3(giveShadeInt("#D500F9")),
    PURPLE_ACCENT_4(giveShadeInt("#AA00FF")),

    DEEP_PURPLE_LIGHTEN_5(giveShadeInt("#EDE7F6")),
    DEEP_PURPLE_LIGHTEN_4(giveShadeInt("#D1C4E9")),
    DEEP_PURPLE_LIGHTEN_3(giveShadeInt("#B39DDB")),
    DEEP_PURPLE_LIGHTEN_2(giveShadeInt("#9575CD")),
    DEEP_PURPLE_LIGHTEN_1(giveShadeInt("#7E57C2")),
    DEEP_PURPLE(giveShadeInt("#673AB7")),
    DEEP_PURPLE_DARKEN_1(giveShadeInt("#5E35B1")),
    DEEP_PURPLE_DARKEN_2(giveShadeInt("#512DA8")),
    DEEP_PURPLE_DARKEN_3(giveShadeInt("#4527A0")),
    DEEP_PURPLE_DARKEN_4(giveShadeInt("#311B92")),
    DEEP_PURPLE_ACCENT_1(giveShadeInt("#B388FF")),
    DEEP_PURPLE_ACCENT_2(giveShadeInt("#7C4DFF")),
    DEEP_PURPLE_ACCENT_3(giveShadeInt("#651FFF")),
    DEEP_PURPLE_ACCENT_4(giveShadeInt("#6200EA")),

    INDIGO_LIGHTEN_5(giveShadeInt("#E8EAF6")),
    INDIGO_LIGHTEN_4(giveShadeInt("#C5CAE9")),
    INDIGO_LIGHTEN_3(giveShadeInt("#9FA8DA")),
    INDIGO_LIGHTEN_2(giveShadeInt("#7986CB")),
    INDIGO_LIGHTEN_1(giveShadeInt("#5C6BC0")),
    INDIGO(giveShadeInt("#3F51B5")),
    INDIGO_DARKEN_1(giveShadeInt("#3949AB")),
    INDIGO_DARKEN_2(giveShadeInt("#303F9F")),
    INDIGO_DARKEN_3(giveShadeInt("#283593")),
    INDIGO_DARKEN_4(giveShadeInt("#1A237E")),
    INDIGO_ACCENT_1(giveShadeInt("#8C9EFF")),
    INDIGO_ACCENT_2(giveShadeInt("#536DFE")),
    INDIGO_ACCENT_3(giveShadeInt("#3D5AFE")),
    INDIGO_ACCENT_4(giveShadeInt("#304FFE")),

    BLUE_LIGHTEN_5(giveShadeInt("#E3F2FD")),
    BLUE_LIGHTEN_4(giveShadeInt("#BBDEFB")),
    BLUE_LIGHTEN_3(giveShadeInt("#90CAF9")),
    BLUE_LIGHTEN_2(giveShadeInt("#64B5F6")),
    BLUE_LIGHTEN_1(giveShadeInt("#42A5F5")),
    BLUE(giveShadeInt("#2196F3")),
    BLUE_DARKEN_1(giveShadeInt("#1E88E5")),
    BLUE_DARKEN_2(giveShadeInt("#1976D2")),
    BLUE_DARKEN_3(giveShadeInt("#1565C0")),
    BLUE_DARKEN_4(giveShadeInt("#0D47A1")),
    BLUE_ACCENT_1(giveShadeInt("#82B1FF")),
    BLUE_ACCENT_2(giveShadeInt("#448AFF")),
    BLUE_ACCENT_3(giveShadeInt("#2979FF")),
    BLUE_ACCENT_4(giveShadeInt("#2962FF")),

    LIGHT_BLUE_LIGHTEN_5(giveShadeInt("#E1F5FE")),
    LIGHT_BLUE_LIGHTEN_4(giveShadeInt("#B3E5FC")),
    LIGHT_BLUE_LIGHTEN_3(giveShadeInt("#81D4FA")),
    LIGHT_BLUE_LIGHTEN_2(giveShadeInt("#4FC3F7")),
    LIGHT_BLUE_LIGHTEN_1(giveShadeInt("#29B6FC")),
    LIGHT_BLUE(giveShadeInt("#03A9F4")),
    LIGHT_BLUE_DARKEN_1(giveShadeInt("#039BE5")),
    LIGHT_BLUE_DARKEN_2(giveShadeInt("#0288D1")),
    LIGHT_BLUE_DARKEN_3(giveShadeInt("#0277BD")),
    LIGHT_BLUE_DARKEN_4(giveShadeInt("#01579B")),
    LIGHT_BLUE_ACCENT_1(giveShadeInt("#80D8FF")),
    LIGHT_BLUE_ACCENT_2(giveShadeInt("#40C4FF")),
    LIGHT_BLUE_ACCENT_3(giveShadeInt("#00B0FF")),
    LIGHT_BLUE_ACCENT_4(giveShadeInt("#0091EA")),

    CYAN_LIGHTEN_5(giveShadeInt("#E0F7FA")),
    CYAN_LIGHTEN_4(giveShadeInt("#B2EBF2")),
    CYAN_LIGHTEN_3(giveShadeInt("#80DEEA")),
    CYAN_LIGHTEN_2(giveShadeInt("#4DD0E1")),
    CYAN_LIGHTEN_1(giveShadeInt("#26C6DA")),
    CYAN(giveShadeInt("#00BCD4")),
    CYAN_DARKEN_1(giveShadeInt("#00ACC1")),
    CYAN_DARKEN_2(giveShadeInt("#0097A7")),
    CYAN_DARKEN_3(giveShadeInt("#00838F")),
    CYAN_DARKEN_4(giveShadeInt("#006064")),
    CYAN_ACCENT_1(giveShadeInt("#84FFFF")),
    CYAN_ACCENT_2(giveShadeInt("#18FFFF")),
    CYAN_ACCENT_3(giveShadeInt("#00E5FF")),
    CYAN_ACCENT_4(giveShadeInt("#00B8D4")),

    TEAL_LIGHTEN_5(giveShadeInt("#E0F2F1")),
    TEAL_LIGHTEN_4(giveShadeInt("#B2DFDB")),
    TEAL_LIGHTEN_3(giveShadeInt("#80CBC4")),
    TEAL_LIGHTEN_2(giveShadeInt("#4DB6AC")),
    TEAL_LIGHTEN_1(giveShadeInt("#26A69A")),
    TEAL(giveShadeInt("#009688")),
    TEAL_DARKEN_1(giveShadeInt("#00897B")),
    TEAL_DARKEN_2(giveShadeInt("#00796B")),
    TEAL_DARKEN_3(giveShadeInt("#00695C")),
    TEAL_DARKEN_4(giveShadeInt("#004D40")),
    TEAL_ACCENT_1(giveShadeInt("#A7FFEB")),
    TEAL_ACCENT_2(giveShadeInt("#64FFDA")),
    TEAL_ACCENT_3(giveShadeInt("#1DE9B6")),
    TEAL_ACCENT_4(giveShadeInt("#00BFA5")),

    GREEN_LIGHTEN_5(giveShadeInt("#E8F5E9")),
    GREEN_LIGHTEN_4(giveShadeInt("#C8E6C9")),
    GREEN_LIGHTEN_3(giveShadeInt("#A5D6A7")),
    GREEN_LIGHTEN_2(giveShadeInt("#81C784")),
    GREEN_LIGHTEN_1(giveShadeInt("#66BB6A")),
    GREEN(giveShadeInt("#4CAF50")),
    GREEN_DARKEN_1(giveShadeInt("#43A047")),
    GREEN_DARKEN_2(giveShadeInt("#388E3C")),
    GREEN_DARKEN_3(giveShadeInt("#2E7D32")),
    GREEN_DARKEN_4(giveShadeInt("#1B5E20")),
    GREEN_ACCENT_1(giveShadeInt("#B9F6CA")),
    GREEN_ACCENT_2(giveShadeInt("#69F0AE")),
    GREEN_ACCENT_3(giveShadeInt("#00E676")),
    GREEN_ACCENT_4(giveShadeInt("#00C853")),

    LIGHT_GREEN_LIGHTEN_5(giveShadeInt("#F1F8E9")),
    LIGHT_GREEN_LIGHTEN_4(giveShadeInt("#DCEDC8")),
    LIGHT_GREEN_LIGHTEN_3(giveShadeInt("#C5E1A5")),
    LIGHT_GREEN_LIGHTEN_2(giveShadeInt("#AED581")),
    LIGHT_GREEN_LIGHTEN_1(giveShadeInt("#9CCC65")),
    LIGHT_GREEN(giveShadeInt("#8BC34A")),
    LIGHT_GREEN_DARKEN_1(giveShadeInt("#7CB342")),
    LIGHT_GREEN_DARKEN_2(giveShadeInt("#689F38")),
    LIGHT_GREEN_DARKEN_3(giveShadeInt("#558B2F")),
    LIGHT_GREEN_DARKEN_4(giveShadeInt("#33691E")),
    LIGHT_GREEN_ACCENT_1(giveShadeInt("#CCFF90")),
    LIGHT_GREEN_ACCENT_2(giveShadeInt("#B2FF59")),
    LIGHT_GREEN_ACCENT_3(giveShadeInt("#76FF03")),
    LIGHT_GREEN_ACCENT_4(giveShadeInt("#64DD17")),

    LIME_LIGHTEN_5(giveShadeInt("#F9FBE7")),
    LIME_LIGHTEN_4(giveShadeInt("#F0F4C3")),
    LIME_LIGHTEN_3(giveShadeInt("#E6EE9C")),
    LIME_LIGHTEN_2(giveShadeInt("#DCE775")),
    LIME_LIGHTEN_1(giveShadeInt("#D4E157")),
    LIME(giveShadeInt("#CDDC39")),
    LIME_DARKEN_1(giveShadeInt("#C0CA33")),
    LIME_DARKEN_2(giveShadeInt("#A4B42B")),
    LIME_DARKEN_3(giveShadeInt("#9E9D24")),
    LIME_DARKEN_4(giveShadeInt("#827717")),
    LIME_ACCENT_1(giveShadeInt("#F4FF81")),
    LIME_ACCENT_2(giveShadeInt("#EEFF41")),
    LIME_ACCENT_3(giveShadeInt("#C6FF00")),
    LIME_ACCENT_4(giveShadeInt("#AEEA00")),

    YELLOW_LIGHTEN_5(giveShadeInt("#FFFDE7")),
    YELLOW_LIGHTEN_4(giveShadeInt("#FFF9C4")),
    YELLOW_LIGHTEN_3(giveShadeInt("#FFF590")),
    YELLOW_LIGHTEN_2(giveShadeInt("#FFF176")),
    YELLOW_LIGHTEN_1(giveShadeInt("#FFEE58")),
    YELLOW(giveShadeInt("#FFEB3B")),
    YELLOW_DARKEN_1(giveShadeInt("#FDD835")),
    YELLOW_DARKEN_2(giveShadeInt("#FBC02D")),
    YELLOW_DARKEN_3(giveShadeInt("#F9A825")),
    YELLOW_DARKEN_4(giveShadeInt("#F57F17")),
    YELLOW_ACCENT_1(giveShadeInt("#FFFF82")),
    YELLOW_ACCENT_2(giveShadeInt("#FFFF00")),
    YELLOW_ACCENT_3(giveShadeInt("#FFEA00")),
    YELLOW_ACCENT_4(giveShadeInt("#FFD600")),

    AMBER_LIGHTEN_5(giveShadeInt("#FFF8E1")),
    AMBER_LIGHTEN_4(giveShadeInt("#FFECB3")),
    AMBER_LIGHTEN_3(giveShadeInt("#FFE082")),
    AMBER_LIGHTEN_2(giveShadeInt("#FFD54F")),
    AMBER_LIGHTEN_1(giveShadeInt("#FFCA28")),
    AMBER(giveShadeInt("#FFC107")),
    AMBER_DARKEN_1(giveShadeInt("#FFB300")),
    AMBER_DARKEN_2(giveShadeInt("#FFA000")),
    AMBER_DARKEN_3(giveShadeInt("#FF8F00")),
    AMBER_DARKEN_4(giveShadeInt("#FF6F00")),
    AMBER_ACCENT_1(giveShadeInt("#FFE57F")),
    AMBER_ACCENT_2(giveShadeInt("#FFD740")),
    AMBER_ACCENT_3(giveShadeInt("#FFC400")),
    AMBER_ACCENT_4(giveShadeInt("#FFAB00")),

    ORANGE_LIGHTEN_5(giveShadeInt("#FFF3E0")),
    ORANGE_LIGHTEN_4(giveShadeInt("#FFEB20")),
    ORANGE_LIGHTEN_3(giveShadeInt("#FFCC80")),
    ORANGE_LIGHTEN_2(giveShadeInt("#FFB74D")),
    ORANGE_LIGHTEN_1(giveShadeInt("#FFA726")),
    ORANGE(giveShadeInt("#FF9800")),
    ORANGE_DARKEN_1(giveShadeInt("#FB8C00")),
    ORANGE_DARKEN_2(giveShadeInt("#F57C00")),
    ORANGE_DARKEN_3(giveShadeInt("#EF6C00")),
    ORANGE_DARKEN_4(giveShadeInt("#E65100")),
    ORANGE_ACCENT_1(giveShadeInt("#FFD180")),
    ORANGE_ACCENT_2(giveShadeInt("#FFAB40")),
    ORANGE_ACCENT_3(giveShadeInt("#FF9100")),
    ORANGE_ACCENT_4(giveShadeInt("#FF6D00")),

    DEEP_ORANGE_LIGHTEN_5(giveShadeInt("#FBE9A7")),
    DEEP_ORANGE_LIGHTEN_4(giveShadeInt("#FFCCBC")),
    DEEP_ORANGE_LIGHTEN_3(giveShadeInt("#FFAB91")),
    DEEP_ORANGE_LIGHTEN_2(giveShadeInt("#FF8A65")),
    DEEP_ORANGE_LIGHTEN_1(giveShadeInt("#FF7043")),
    DEEP_ORANGE(giveShadeInt("#FF5722")),
    DEEP_ORANGE_DARKEN_1(giveShadeInt("#F4511E")),
    DEEP_ORANGE_DARKEN_2(giveShadeInt("#E64A19")),
    DEEP_ORANGE_DARKEN_3(giveShadeInt("#D84315")),
    DEEP_ORANGE_DARKEN_4(giveShadeInt("#BF360C")),
    DEEP_ORANGE_ACCENT_1(giveShadeInt("#FF9E80")),
    DEEP_ORANGE_ACCENT_2(giveShadeInt("#FF6E40")),
    DEEP_ORANGE_ACCENT_3(giveShadeInt("#FF3D00")),
    DEEP_ORANGE_ACCENT_4(giveShadeInt("#DD2600")),

    BROWN_LIGHTEN_5(giveShadeInt("#EFEBE9")),
    BROWN_LIGHTEN_4(giveShadeInt("#D7CCC8")),
    BROWN_LIGHTEN_3(giveShadeInt("#BCAAA4")),
    BROWN_LIGHTEN_2(giveShadeInt("#A1887F")),
    BROWN_LIGHTEN_1(giveShadeInt("#8D6E63")),
    BROWN(giveShadeInt("#795548")),
    BROWN_DARKEN_1(giveShadeInt("#6D4C41")),
    BROWN_DARKEN_2(giveShadeInt("#5D4037")),
    BROWN_DARKEN_3(giveShadeInt("#4E342E")),
    BROWN_DARKEN_4(giveShadeInt("#3E2723")),

    GREY_LIGHTEN_5(giveShadeInt("#FAFAFA")),
    GREY_LIGHTEN_4(giveShadeInt("#F5F5F5")),
    GREY_LIGHTEN_3(giveShadeInt("#EEEEEE")),
    GREY_LIGHTEN_2(giveShadeInt("#E0E0E0")),
    GREY_LIGHTEN_1(giveShadeInt("#BDBDBD")),
    GREY(giveShadeInt("#9E9E9E")),
    GREY_DARKEN_1(giveShadeInt("#757575")),
    GREY_DARKEN_2(giveShadeInt("#616161")),
    GREY_DARKEN_3(giveShadeInt("#424242")),
    GREY_DARKEN_4(giveShadeInt("#212121")),

    BLACK(giveShadeInt("#000000")),
    WHITE(giveShadeInt("#FFFFFF")),

    BLUE_GREY_LIGHTEN_5(giveShadeInt("#ECEFF1")),
    BLUE_GREY_LIGHTEN_4(giveShadeInt("#CFD8DC")),
    BLUE_GREY_LIGHTEN_3(giveShadeInt("#B0BBC5")),
    BLUE_GREY_LIGHTEN_2(giveShadeInt("#90A4AE")),
    BLUE_GREY_LIGHTEN_1(giveShadeInt("#78909C")),
    BLUE_GREY(giveShadeInt("#607D8B")),
    BLUE_GREY_DARKEN_1(giveShadeInt("#546E7A")),
    BLUE_GREY_DARKEN_2(giveShadeInt("#455A64")),
    BLUE_GREY_DARKEN_3(giveShadeInt("#37474F")),
    BLUE_GREY_DARKEN_4(giveShadeInt("#263238"));
    

    int shade;

    MaterialShadeEnum(int shade){
        this.shade = shade;
    }

    public int getShade(){
        return shade;
    }

    public static int giveShadeInt(String string){
        return Color.parseColor(string);
    }

}
