package awe.devikamehra.shademelange.Enum;

import android.graphics.Color;

/**
 * Created by Devika on 26-12-2015.
 */
public enum ShadeEnum {

    WHITE(giveShadeInt("#FFFFFF")),
    IVORY(giveShadeInt("#FFFFF0")),
    LIGHT_YELLOW(giveShadeInt("#FFFFE0")),
    YELLOW(giveShadeInt("#FFFF00")),
    SNOW(giveShadeInt("#FFFAFA")),
    FLORAL_WHITE(giveShadeInt("#FFFAF0")),
    LEMON_CHIFFON(giveShadeInt("#FFFACD")),
    CORN_SILK(giveShadeInt("#FFF8DC")),
    SEA_SHELL(giveShadeInt("#FFF5EE")),
    LAVENDER_BLUSH(giveShadeInt("#FFF0F5")),
    PAPAYA_WHIP(giveShadeInt("#FFEFD5")),
    BLANCHED_ALMOND(giveShadeInt("#FFEBCD")),
    MISTY_ROSE(giveShadeInt("#FFE4E1")),
    BISQUE(giveShadeInt("#FFE4C4")),
    MOCCASIN(giveShadeInt("#FFE4B5")),
    NAVAJO_WHITE(giveShadeInt("#FFDEAD")),
    PEACH_PUFF(giveShadeInt("#FFDAB9")),
    GOLD(giveShadeInt("#FFD700")),
    PINK(giveShadeInt("#FFC0CB")),
    LIGHT_PINK(giveShadeInt("#FFB6C1")),
    ORANGE(giveShadeInt("#FFA500")),
    LIGHT_SALMON(giveShadeInt("#FFA07A")),
    DARK_ORANGE(giveShadeInt("#FF8C00")),
    CORAL(giveShadeInt("#FF7F50")),
    HOT_PINK(giveShadeInt("#FF69B4")),
    TOMATO(giveShadeInt("#FF6347")),
    ORANGE_RED(giveShadeInt("#FF4500")),
    DEEP_PINK(giveShadeInt("#FF1493")),
    FUCHSIA(giveShadeInt("#FF00FF")),
    MAGENTA(giveShadeInt("#FF00FF")),
    RED(giveShadeInt("#FF0000")),
    OLD_LACE(giveShadeInt("#FDF5E6")),
    LIGHT_GOLDEN_ROD_YELLOW(giveShadeInt("#FAFAD2")),
    LINEN(giveShadeInt("#FAF0E6")),
    ANTIQUE_WHITE(giveShadeInt("#FAEBD7")),
    SALMON(giveShadeInt("#FA8072")),
    GHOST_WHITE(giveShadeInt("#F8F8FF")),
    MINT_CREAM(giveShadeInt("#F5FFFA")),
    WHITE_SMOKE(giveShadeInt("#F5F5F5")),
    BEIGE(giveShadeInt("#F5F5DC")),
    WHEAT(giveShadeInt("#F5DEB3")),
    SANDY_BROWN(giveShadeInt("#F4A460")),
    AZURE(giveShadeInt("#F0FFFF")),
    HONEYDEW(giveShadeInt("#F0FFF0")),
    ALICE_BLUE(giveShadeInt("#F0F8FF")),
    KHAKI(giveShadeInt("#F0E68C")),
    LIGHT_CORAL(giveShadeInt("#F08080")),
    PALE_GOLDEN_ROD(giveShadeInt("#EEE8AA")),
    VIOLET(giveShadeInt("#EE82EE")),
    DARK_SALMON(giveShadeInt("#E9967A")),
    LAVENDER(giveShadeInt("#E6E6FA")),
    LIGHT_CYAN(giveShadeInt("#E0FFFF")),
    BURLY_WOOD(giveShadeInt("#DEB887")),
    PLUM(giveShadeInt("#DDA0DD")),
    GAINS_BORO(giveShadeInt("#DCDCDC")),
    CRIMSON(giveShadeInt("#DC143C")),
    PALE_VIOLET_RED(giveShadeInt("#DB7093")),
    GOLDENROD(giveShadeInt("#DAA520")),
    ORCHID(giveShadeInt("#DA70D6")),
    THISTLE(giveShadeInt("#D8BFD8")),
    LIGHT_GREY(giveShadeInt("#D3D3D3")),
    TAN(giveShadeInt("#D2B48C")),
    CHOCOLATE(giveShadeInt("#D2691E")),
    PERU(giveShadeInt("#CD853F")),
    INDIAN_RED(giveShadeInt("#CD5C5C")),
    MEDIUM_VIOLET_RED(giveShadeInt("#C71585")),
    SILVER(giveShadeInt("#C0C0C0")),
    DARK_KHAKI(giveShadeInt("#BDB76B")),
    ROSY_BROWN(giveShadeInt("#BC8F8F")),
    MEDIUM_ORCHID(giveShadeInt("#BA55D3")),
    DARK_GOLDEN_ROD(giveShadeInt("#B8860B")),
    FIREBRICK(giveShadeInt("#B22222")),
    POWDER_BLUE(giveShadeInt("#B0E0E6")),
    LIGHT_STEEL_BLUE(giveShadeInt("#B0C4DE")),
    PALE_TURQUOISE(giveShadeInt("#AFEEEE")),
    GREEN_YELLOW(giveShadeInt("#ADFF2F")),
    LIGHT_BLUE(giveShadeInt("#ADD8E6")),
    DARK_GRAY(giveShadeInt("#A9A9A9")),
    BROWN(giveShadeInt("#A52A2A")),
    SIENNA(giveShadeInt("#A0522D")),
    YELLOW_GREEN(giveShadeInt("#9ACD32")),
    DARK_ORCHID(giveShadeInt("#9932CC")),
    PALE_GREEN(giveShadeInt("#98FB98")),
    DARK_VIOLET(giveShadeInt("#9400D3")),
    MEDIUM_PURPLE(giveShadeInt("#9370DB")),
    LIGHT_GREEN(giveShadeInt("#90EE90")),
    DARK_SEA_GREEN(giveShadeInt("#8FBC8F")),
    SADDLE_BROWN(giveShadeInt("#8B4513")),
    DARK_MAGENTA(giveShadeInt("#8B008B")),
    DARK_RED(giveShadeInt("#8B0000")),
    BLUE_VIOLET(giveShadeInt("#8A2BE2")),
    LIGHT_SKY_BLUE(giveShadeInt("#87CEFA")),
    SKY_BLUE(giveShadeInt("#87CEEB")),
    GRAY(giveShadeInt("#808080")),
    OLIVE(giveShadeInt("#808000")),
    PURPLE(giveShadeInt("#800080")),
    MAROON(giveShadeInt("#800000")),
    AQUAMARINE(giveShadeInt("#7FFFD4")),
    CHARTREUSE(giveShadeInt("#7FFF00")),
    LAWN_GREEN(giveShadeInt("#7CFC00")),
    MEDIUM_SLATE_BLUE(giveShadeInt("#7B68EE")),
    LIGHT_SLATE_GRAY(giveShadeInt("#778899")),
    SLATE_GRAY(giveShadeInt("#708090")),
    OLIVE_DRAB(giveShadeInt("#6B8E23")),
    SLATE_BLUE(giveShadeInt("#6A5ACD")),
    DIM_GRAY(giveShadeInt("#696969")),
    MEDIUM_AQUA_MARINE(giveShadeInt("#66CDAA")),
    CORN_FLOWER_BLUE(giveShadeInt("#6495ED")),
    CADET_BLUE(giveShadeInt("#5F9EA0")),
    DARK_OLIVE_GREEN(giveShadeInt("#556B2F")),
    INDIGO(giveShadeInt("#4B0082")),
    MEDIUM_TURQUOISE(giveShadeInt("#48D1CC")),
    DARK_SLATEBLUE(giveShadeInt("#483D8B")),
    STEEL_BLUE(giveShadeInt("#4682B4")),
    ROYAL_BLUE(giveShadeInt("#4169E1")),
    TURQUOISE(giveShadeInt("#40E0D0")),
    MEDIUM_SEAGREEN(giveShadeInt("#3CB371")),
    LIME_GREEN(giveShadeInt("#32CD32")),
    DARK_SLATE_GRAY(giveShadeInt("#2F4F4F")),
    SEA_GREEN(giveShadeInt("#2E8B57")),
    FOREST_GREEN(giveShadeInt("#228B22")),
    LIGHT_SEA_GREEN(giveShadeInt("#20B2AA")),
    DODGER_BLUE(giveShadeInt("#1E90FF")),
    MID_NIGHT_BLUE(giveShadeInt("#191970")),
    AQUA(giveShadeInt("#00FFFF")),
    CYAN(giveShadeInt("#00FFFF")),
    SPRING_GREEN(giveShadeInt("#00FF7F")),
    LIME(giveShadeInt("#00FF00")),
    MEDIUM_SPRING_GREEN(giveShadeInt("#00FA9A")),
    DARK_TURQUOISE(giveShadeInt("#00CED1")),
    DEEP_SKY_BLUE(giveShadeInt("#00BFFF")),
    DARK_CYAN(giveShadeInt("#008B8B")),
    TEAL(giveShadeInt("#008080")),
    GREEN(giveShadeInt("#008000")),
    DARK_GREEN(giveShadeInt("#006400")),
    BLUE(giveShadeInt("#0000FF")),
    MEDIUM_BLUE(giveShadeInt("#0000CD")),
    DARK_BLUE(giveShadeInt("#00008B")),
    NAVY(giveShadeInt("#000080")),
    BLACK(giveShadeInt("#000000"));

    int shade;

    ShadeEnum(int shade){
        this.shade = shade;
    }

    public int getShade(){
        return shade;
    }

    public static int giveShadeInt(String string){
        return Color.parseColor(string);
    }
}

